version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myDb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin 

# To use a persistent volume for data persistence
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./message.sql:/docker-entrypoint-initdb.d/message.sql
    ports:
      - "3306:3306"
    networks:
      two-tier:
  
  
  
  
  flask-app: 
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: flask-app 
    ports:
      - "5000:5000"
    networks:
      - two-tier
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DB: myDb
    restart: always

networks:
  two-tier:
