apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - name: myapp
    image: pias97/ci_cd_image:latest
    env:
      - name: MYSQL_HOST
        value: "none"
      - name: MYSQL_PASSWORD
        value: "admin"
      - name: MYSQL_USER
        value: "admin"
      - name: MYSQL_DB
        value: "myDb"
    ports:
      - containerPort: 80

    imagePullPolicy: Always
