apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
    - name: my-flask-app
      image: pias97/two-tier-flask-app:latest
      env:
        - name: MYSQL_HOST
          value: "none" # will fill later
        - name: MYSQL_PASSWORD
          value: "admin"
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_DB
          value: "myDb"
      ports:
        - containerPort: 5000

      imagePullPolicy: Always
