apiVersion: apps/v1
kind: Service
metadata:
  name: my-flask-app
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
  type: NodePort


